# -----------------------------------------------------------------------------------------
#Copyright CompanyNameMagicTag 2018-2019.All rights reserved
#Author: CompanyName
#------------------------------------------------------------------------------------------
app/mrs/cco
app/mrs/common
app/mrs/dfx
app/mrs/include
app/mrs/proto
app/mrs/sta
app/mrs/ndm